version: "3.9"

services:

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  china:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    build: ./china-backend
    volumes:
      - ./static:/code/static
    ports:
      - "8000:8000"
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "db:5432"
      DB_NAME: "${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"